_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "checkpoints/food/faster_rcnn/faster_rcnn_R_101_FPN_base/model_final.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 53
    OUTPUT_LAYER: "FastRCNNOutputLayers"
    FREEZE_FEAT: True
  BACKBONE:
    FREEZE: True
  PROPOSAL_GENERATOR:
    FREEZE: True
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ('food53_base_train_10_shot','food53_novel_train_10_shot',)
  TEST: ('food53_base_val','food53_novel_val')
DATALOADER:
  SAMPLER_TRAIN: "RepeatFactorTrainingSampler"
  REPEAT_THRESHOLD: 0.95
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.0001
  STEPS: (30000,)
  MAX_ITER: 40000
  CHECKPOINT_PERIOD: 5000
  WARMUP_ITERS: 0
TEST:
  EVAL_PERIOD: 500
OUTPUT_DIR: "checkpoints/food/faster_rcnn/faster_rcnn_R_101_FPN_ft_10shot"