_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "checkpoints/food/faster_rcnn/faster_rcnn_R_101_FPN_ft_meta/model_final.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 53
    OUTPUT_LAYER: "CosineSimOutputLayers"
    COSINE_SCALE: -1.
    FREEZE_FEAT: False
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
  BACKBONE:
    FREEZE: True
  PROPOSAL_GENERATOR:
    FREEZE: True
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ('food53_base_train_5_shot','food53_novel_train_5_shot')
SOLVER:
  IMS_PER_BATCH: 1
  BASE_LR: 0.001
  STEPS: (1000,)
  MAX_ITER: 1000
  CHECKPOINT_PERIOD: 10000
  WARMUP_ITERS: 0
TEST:
  EVAL_PERIOD: 500
OUTPUT_DIR: "checkpoints/food/faster_rcnn/faster_rcnn_R_101_FPN_ft_extract_features"